SELECT DEPARTMENT_NAME,CATEGORY FROM TB_DEPARTMENT;

SELECT DEPARTMENT_NAME||'의 정원은 '||CAPACITY||'명 입니다.' FROM TB_DEPARTMENT;

SELECT STUDENT_NAME FROM TB_STUDENT 
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '국어국문학과' 
AND ABSENCE_YN = 'Y' AND STUDENT_SSN LIKE '_______2%';

SELECT STUDENT_NAME FROM TB_STUDENT
WHERE STUDENT_NO LIKE 'A513%' 
and STUDENT_NAME LIKE '%경희' 
OR STUDENT_NAME LIKE '%경훈' OR STUDENT_NAME LIKE '%경환';

SELECT DEPARTMENT_NAME,CATEGORY FROM TB_DEPARTMENT
WHERE CAPACITY <= 30 AND CAPACITY >= 20
ORDER BY 1;

SELECT PROFESSOR_NAME FROM TB_PROFESSOR P
JOIN TB_CLASS_PROFESSOR C  ON P.PROFESSOR_NO = C.PROFESSOR_NO
WHERE C.CLASS_NO IS NULL;

select * from tb_professor where department_no is null;

SELECT STUDENT_NAME,DEPARTMENT_NO FROM TB_STUDENT
WHERE DEPARTMENT_NO IS NULL;

SELECT STUDENT_NAME FROM TB_STUDENT
WHERE STUDENT_NAME IS NULL;

SELECT CLASS_NO FROM TB_CLASS
WHERE PREATTENDING_CLASS_NO IS NOT NULL;

SELECT DISTINCT CATEGORY FROM TB_DEPARTMENT ; 
-- DISTINCT 중복 제거

SELECT STUDENT_NO,STUDENT_NAME,STUDENT_SSN FROM TB_STUDENT
WHERE STUDENT_NO LIKE 'A2%' AND STUDENT_ADDRESS LIKE '%전주%' AND
ABSENCE_YN = 'N' ORDER BY STUDENT_NAME;

SELECT STUDENT_NO "학번",STUDENT_NAME "이름",ENTRANCE_DATE "입학년도" FROM TB_STUDENT
WHERE DEPARTMENT_NO = '002'
ORDER BY ENTRANCE_DATE;

SELECT PROFESSOR_NAME,PROFESSOR_SSN FROM TB_PROFESSOR
WHERE PROFESSOR_NAME NOT LIKE '___';

SELECT PROFESSOR_NAME "교수이름",
TRUNC(MONTHS_BETWEEN(SYSDATE,
SUBSTR(PROFESSOR_SSN,1,2)||'/'||
SUBSTR(PROFESSOR_SSN,3,2)||'/'||SUBSTR(PROFESSOR_SSN,5,2)))/12 "나이" 
FROM TB_PROFESSOR
WHERE SUBSTR (PROFESSOR_SSN, 8, 1) = '1' 
ORDER BY PROFESSOR_SSN DESC;








