-- DDL
COMMIT;
-- Data Definion Language
-- 오라클의 객체를 생성,수정,삭제하는 명령어, 명령어의 종류로는
-- CREATE, ALTER, DROP, TRUNCATE ...

DESC EMPLOYEE;

DESC USER_UNIQUE;

DESC SHOP_MEMBER;

DESC SHOP_BUY;


-- 계정을 만들어주세요
-- 접속정보 (ID/PW) : KH / KH
-- 접속 권한 : 생성권한 부여

DROP USER KH CASCADE;
CREATE USER KH IDENTIFIED BY KH;

GRANT RESOURCE TO KH;

grant connect to kh;

-- kh violet
-- ALTER(오라클 객체)
-- ALTER를 이용한제약조건 추가, 수정, 이름변경
-- ALTER를 이용한 컬럼 추가, 컬럼 데이터타입 수정,컬럼명 수정,컬럼 삭제,테이블명 수정
SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'EMPLOYEE';
SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'DEPARTMENT';
-- ** CONSTRAINTS TYPE
-- P : PRIMARY KEY
-- R : FORELGN KEY
-- C : CHECK OR NOT NULL
-- U : UNIQUE

CREATE TABLE USER_GRADE(
    GRADE_CODE NUMBER PRIMARY KEY,
    GRADE_NAME VARCHAR2(30) NOT NULL
);

DROP TABLE USER_FOREIGN_KEY;
DROP TABLE USER_GRADE;

INSERT INTO USER_GRADE VALUES(10, '일반회원');
INSERT INTO USER_GRADE VALUES(20, '우수회원');
INSERT INTO USER_GRADE VALUES(30, '특별회원');
INSERT INTO USER_GRADE VALUES(40, 'VIP회원');
DELETE FROM USER_GRADE WHERE GRADE_CODE = 40;
SELECT * FROM USER_GRADE;

CREATE TABLE USER_FOREIGN_KEY(
    USER_NO NUMBER,
    USER_ID VARCHAR2(20),
    USER_PWD VARCHAR2(30),
    USER_NAME VARCHAR2(30),
    USER_GENDER VARCHAR2(10),
    USER_PHONE VARCHAR2(30),
    USER_EMAIL VARCHAR2(50),
    USER_DATE DATE DEFAULT SYSDATE,
    GRADE_CODE NUMBER
);
INSERT INTO USER_FOREIGN_KEY
VALUES(1, 'khuser01', 'pass01', '일용자', 'M', null, null, DEFAULT, 10);
INSERT INTO USER_FOREIGN_KEY
VALUES(2, 'khuser02', 'pass02', '이용자', 'M', null, null, DEFAULT, 20);
INSERT INTO USER_FOREIGN_KEY
VALUES(3, 'khuser03', 'pass03', '삼용자', 'M', null, null, DEFAULT, 30);
INSERT INTO USER_FOREIGN_KEY
VALUES(4, 'khuser04', 'pass04', '사용자', 'M', null, null, DEFAULT, 40);

SELECT * FROM USER_FOREIGN_KEY;

DESC USER_GRADE;
-- 1. 테이블에 컬럼 추가
-- 2. 테이블에 컬럼 삭제
-- 3. 테이블의 컬럼데이터타입 수정
-- 4. 테이블의 컬럼명 수정
-- 5. 테이블명 수정
-- 1. 테이블의 컬럼 추가
ALTER TABLE USER_GRADE
ADD GRADE_DATE DATE;

SELECT * FROM USER_GRADE;

-- 2. 테이블의 컬럼 삭제
ALTER TABLE USER_GRADE
DROP COLUMN GRADE_DATE;

-- 3. 테이블의 컬럼 데이터 타입 수정
ALTER TABLE USER_GRADE
MODIFY GRADE_NAME CHAR(12);

ALTER TABLE USER_GRADE
ADD GRADE_DATE DATE;

--4 테이블의 컬럼명 수정
ALTER TABLE USER_GRADE
RENAME COLUMN GRADE_DATE TO PEG_DATE;

SELECT * FROM USER_GRADE;

-- 5 테이블 명 수정
ALTER TABLE USER_GRADE
RENAME TO GRADE_TBL;


SELECT * FROM GRADE_TBL;

RENAME GRADE_TBL TO USER_GRADE;


SELECT * FROM USER_GRADE;

-- 제약조건과 ALTER
-- 1. 제약 조건 추가
-- 2. 제약 조건 삭제
-- 3. 제약 조건 수정

DROP TABLE USER_GRADE;
DROP TABLE USER_FOREIGN_KEY;
-- 1. 제약조건 추가

ALTER TABLE USER_GRADE
ADD CONSTRAINT PK_GRADE_CODE PRIMARY(GRADE_CODE);

ALTER TABLE USER_FOREIGN_KEY
ADD CONSTRAINT PK_GRADE_CODE FOREIGN KEY(GRADE_CODE)
REFERENCES USER_GRADE(GRADE_CODE);
-- SYS_ -> PK_GRADE_CODE
-- 2. 제약 조건 삭제
ALTER TABLE USER_GRADE
DROP CONSTRAINT SYS_C007123;

-- ex01) USER_FOREIGN_KEY 테이블에 USER_DATE DATE 컬럼을 추가해주세요
-- ex02) USER_FOREIGN_KEY 테이블에 USER_DATE DATE 컬럼을 삭제해주세요
-- ex03) USER_FOREIGN_KEY 테이블에 USER_DATE 컬럼의 자료형을 VARCHAR2(10)으로 바꿔주세요
-- ex04) USER_FOREIGN_KEY 테이블에 USER_DATE DATE 컬럼의 이름을 REG_DATE로 
-- 변경해주세요
-- ex05) USER_FOREIGN_KEY 테이블의 이름을 USER_TBL로 바꿔주세요 (2가지)
SELECT * FROM USER_FOREIGN_KEY;

ALTER TABLE USER_FOREIGN_KEY
ADD CONSTRAINT USER_DATE PRIMARY(USER_DATE);

