-- 4일차 집합 연산자
-- 1.1 합집합
-- 1.1.1 UNION UNION ALL(중복허용)
SELECT EMP_NAME, SALARY FROM EMPLOYEE
WHERE DEPT_CODE = 'D5'
UNION
SELECT EMP_NAME,SALARY FROM EMPLOYEE
WHERE SALARY >= 2400000;

SELECT EMP_NAME, SALARY FROM EMPLOYEE
WHERE DEPT_CODE = 'D5'
UNION ALL
SELECT EMP_NAME,TO_NUMBER(EMP_ID) -- 데이터 타입이 같음
FROM EMPLOYEE
WHERE SALARY >= 2400000;

-- UNION 사용조건 1. 컬럼의 개수가 같아야 함.
-- 2. 컬럼의 데이터 타입이 각각 같아야 함

-- 1.2 교집합
-- 1.2.1 INTERSECT
SELECT EMP_NAME, SALARY FROM EMPLOYEE
WHERE DEPT_CODE = 'D5'
INTERSECT
SELECT EMP_NAME,SALARY FROM EMPLOYEE
WHERE SALARY >= 2400000;

-- 1.3 차집합
-- 1.3.1 MINUS
SELECT EMP_NAME, SALARY FROM EMPLOYEE
WHERE DEPT_CODE = 'D5'
MINUS
SELECT EMP_NAME,SALARY FROM EMPLOYEE
WHERE SALARY >= 2400000;

